   Oh Most Grandiose and Fragrant Emacs, please be in -*- org -*- mode!

#+STARTUP: showeverything
#+TAGS: KARL(k) GUNNAR(g)

* Presentation Materials
  - OSCON Session:
    http://www.oscon.com/oscon2012/public/schedule/detail/24221
  - Timeline HTML page:
    http://atechnologyjobisnoexcuse.com/oss-timeline.html
  - Preso spreadsheet:
    https://docs.google.com/document/d/1m0yWgVs-RlNtfUrWZ61D2SSXvH0lpS64h52FF9_lM0U/edit
  - Preso Google Doc (possibly to be obsoleted by this notes file):
    https://docs.google.com/spreadsheet/ccc?key=0AjxnOozsvYvldHY1NE1MV0pGVXRyd2hUaTAzdmRJb1E#gid=10
  - History of Open Source in Government
    http://opensource.com/government/12/5/history-open-source-government
    http://atechnologyjobisnoexcuse.com/2012/04/history-of-open-source-in-government/

* Tasks
** TODO Gunnar to review pending submissions in timeline spreadsheet, and
   move code release items over to the Scott Goodwin spreadsheet.
** TODO Karl to look into citations from policies to articles.
** TODO Gunnar to look at Fedora contributor agreements
   See if there's any trend regarding receipt from .mil and .gov people.
** TODO Gunnar to add Transparency Camp as an event
** TODO Gunnar to make a list of the really important events/policies,
   just for the purposes of this talk, not as part of the timeline data.
** TODO Karl to expand "Projects" and "Psychology" notes in slides
   List out all the talking points, then go over them with Gunnar.
** TODO Karl to go through the "Policy Dependency Analysis" notes below,
   and move any patterns worth talking about into the slide notes.

* Policy Dependency Analysis                                           :KARL:

  Question: What percentage of “default open” or “contribution”
            policies are preceded by an “OSS is commercial” policy?

            Plus anything else interesting we find in looking at
            policy ordering...

  Answer:   Sample too small to talk about "percentages".  We'll have
            to address this by talking about a few specific cases.

  New Question: Why can't we sort by date in the timeline spreadsheet?

  <<< in progress, feel free to ignore below for now >>>

  Every "PATTERN" noted below is tentative -- they are not
  conclusions yet, they are things to be looked at.

  [2003-05-28] Stenbit memo (use/make)
               http://www.terrybollinger.com/stenbitmemo/stenbitmemo_png/index.html

  [2004-07-01] OMB memo M-04-16 (use)
               http://www.whitehouse.gov/omb/memoranda_fy04_m04-16
               Similar to Stenbit in tone & emphasis.

  [2007-06-05] "Department Of The Navy Open Source Software Guidance"
               Navy CIO Robert Carey's June 2007 memo
               http://www.doncio.navy.mil/Download.aspx?AttachID=261
               States OSS can be considered COTS when it meets the
               definition (which is sort of tautological), then gives
               the definition of COTS, and defines OSS, citing OSI.

  [2009-09-30] Portland, OR Open Source policy (use)
               Specific about favoring open source in acquisition.
               Uses "commercial" for "proprietary", but whatever.
               PATTERN: Terminology tends to be more consistent, and
               generally more correct, among the federal memos?  I
               think this may be true; it may also be unimportant.

  [2009-10-16] DOD "Open Source Memo" (use)
               http://dodcio.defense.gov/Portals/0/Documents/OSSFAQ/2009OSS.pdf
               Reiterates that OSS is COTS, and this time actively
               encourages consideration of open source.

  [2009-12-08] Open Government Directive
               http://mil-oss.org/resources/us-omb_open-government-directive_m10-06.pdf

               Really a transparency and open data policy. It does not
               mention "open source", nor even "software" nor
               "free". But it does define a culture of permissionless
               data sharing and of establishing feedback loops both
               upward

               PATTERN: The closer a policy is to implementation
               level, the more likely it is to be specific in what it
               says about open source.  What this means, then, is if
               you see a grand pronouncement from very high up (e.g.,
               the WH) about open source, that may be less effective
               than the high-middle layer memos that are high enough
               to be obeyed, but low enough to say something specific.

  [2010-01-07] CA open source policy from CIO Teri Takai (use)
               http://www.cio.ca.gov/Government/IT_Policy/pdf/IT_Policy_Letter_10-01_Open_Source_Software.pdf
               Very clear, unambiguous reminder that OSS is to be
               considered. This policy even includes the complete Open
               Source Definition from the OSI.
               
  [2010-06-28] OMB Technology Neutrality memo (use)

  [2010-12-01] SF policy mandating evaluation (use).
               http://govfresh.com/2010/01/san-francisco-releases-new-software-evaluation-policy/
               Policy mandating evaluation of open source in software
               procurement for purchases over $100,000. A little bit
               someone's first trip to the open source store: OSS is
               contrasted with "commercial" software, and is defined
               thusly: "Open source software means that the underlying
               source code is not copyrighted and therefore available
               free of charge to read, modify, and build upon."

  [2011-10-31] DISA AppDev guidelines update (use, borders on make)

               The Defense Information Systems Agency updates its
               guidelines for application development to resolve
               ambiguities and misunderstandings, making it much
               easier to use open source in the DOD. Although the
               document being clarified, the AppDev STIG, is about
               both use and development, this clarification appears to
               only cover use (acquisition).

  [2012-01-18] NH OSS / open data policy (use/?)
               http://www.gencourt.state.nh.us/legislation/2012/HB0418.html

  [2012-04-06] CFPB open source policy (use, make)
  [2012-06-21] CFPB design/tech fellowships (use, make)


* Other Source Material / References

** "Linux Grabs Its Single Biggest Win" article
   http://www.techrepublic.com/blog/opensource/linux-grabs-its-single-biggest-win/3690
   Use this (gently) as an example of legacy attitude -- for example,
   where DoD started off before the Bollinger report.

** Gov't-Released OSS Software w/ Release Dates
   https://docs.google.com/spreadsheet/ccc?key=0AjxnOozsvYvldEZncklySWgtYlYwOGp6S3hDdXVGV3c#gid=0

** http://csrc.nist.gov/groups/STM/cmvp/documents/140-1/1401val2012.htm#1747

   OpenSSL FIPS Object Module
   (Software Version: 2.0)

   (When built, installed, protected and initialized as assumed by the
   Crypto Officer role and as specified in the provided Security
   Policy. Appendix A of the provided Security Policy specifies the
   actual distribution tar file containing the source code of this
   module. There shall be no additions, deletions or alterations to
   the tar file contents as used during module build. The distribution
   tar file shall be verified as specified in Appendix A of the
   provided Security Policy. Installation and protection shall be
   completed as specified in Appendix A of the provided Security
   Policy. Initialization shall be invoked as per Section 4 of the
   provided Security Policy. Any deviation from specified
   verification, protection, installation and initialization
   procedures will result in a non FIPS 140-2 compliant module.)

   Make sure audience understands why these rules are not bad -- tell
   the Debian OpenSSH story.

* http://www.redhat.com/solutions/industry/government/certifications.html
* Current procurement thread w/ CFPB
  Also: http://www.consumerfinance.gov/blog/designtechnology-fellows-changing-the-way-government-works/
* "CAC enabled git" thread in mil-oss for OSCON talk
* "[mil-oss] Open Source'ing utilities written internally by Government Employees" for OSCON talk.
* Government Open Source Policies" report, by James Andrew Lewis
  David Wheeler said to us (on mil-oss):

  If you want to get a quick handle on open source software (OSS)
  policies in governments worldwide, you probably should look at:
  "Government Open Source Policies" by James Andrew Lewis, Center for
  Strategic & International Studies:
  http://csis.org/publication/government-open-source-policies
  
  The last one was April 2010, so it doesn't have the latest, and they
  tend to focus on government-wide (so individual agencies often get
  omitted).  Still, if you want to get an international flavor that's a
  reasonable place to start, and you might at least cite it as a way to
  compare US with other countries.
* [2012-06-07 1-2pm CT] David Wheeler "Lessons Learned" Gov OSS webinar
     In mil-oss:

     Subject: [mil-oss] Webinar June 7, 2-3pm Eastern Time: "Lessons Learned:
      Roadblocks and Opportunities for Open Source Software (OSS) in U.S. Government"
 
    On June 7, 2012, 2-3pm Eastern Time, I’ll be speaking as part of the
    free webinar “Lessons Learned: Roadblocks and Opportunities for Open
    Source Software (OSS) in U.S. Government” hosted by GovLoop.  To
    listen in, go here:
    
    https://event.on24.com/eventRegistration/EventLobbyServlet?target=registration.
    jsp&eventid=462526&sessionid=1&key=E7F3DCDCA57D4521C74872EA9D848A2C&sourcepage=register
    
    I’ll be speaking on some results of a survey about (US federal)
    government & open source software.
    Everyone is welcome!
